/*
 * DO NOT EDIT THIS FILE. Generated by checkmk.
 * Edit the original source file "tests/headers.check" instead.
 */

#include <check.h>

#include "../calc.h"
#include "../calc.h"
START_TEST(t1)
{
  char str[] = "1+5*2+3";
  char origin[] = "152*+3+";
  calc(str);
  ck_assert_str_eq(str, origin);

// #test t2
//   char str[] = "4*5+3-4/2*6";
//   char origin[] = "45*3+42/6*-";
//   calc(str);
//   ck_assert_str_eq(str, origin);

// #test t3
//   char str[] = "cos(3)+sin(2)";
//   char origin[] = "cos(3)+";
//   calc(str);
//   ck_assert_str_eq(str, origin);
}
END_TEST

int main(void)
{
    Suite *s1 = suite_create("Core");
    TCase *tc1_1 = tcase_create("Core");
    SRunner *sr = srunner_create(s1);
    int nf;

    suite_add_tcase(s1, tc1_1);
    tcase_add_test(tc1_1, t1);

    srunner_run_all(sr, CK_ENV);
    nf = srunner_ntests_failed(sr);
    srunner_free(sr);

    return nf == 0 ? 0 : 1;
}
